// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using CreatureModule;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

public class CreatureGameAgent : MonoBehaviour
{
	public CreatureGameController game_controller;

	public CreatureGameAgent ()
	{

	}
			
	public virtual void updateStep()
	{

	}

	public virtual void initState()
	{
	}

    public virtual void AnimationReachedEnd(string anim_name)
    {  
    }
}


